version: '3'
services:
  db:
    image: mysql:5
    container_name: MySQL_Container
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
      - umbrella
networks:
  umbrella:
